#!/bin/sh
set -e

cleanup () {
	if [ -n "$logfile" ]; then
		rm -f "$logfile"
	fi
}
if [ -n "$1" ]; then
	trap cleanup EXIT
	logfile="$(mktemp -t etckeeper-$VCS.XXXXXXXXXX)"
	if [ "x$1" = "x--stdin" ]; then
		cat > "$logfile"
	else
		if [ "x$1" = "x-m" ]; then
			shift 1
		fi
		echo "$1" > "$logfile"
	fi
else
	logfile=""
fi

hostname=`hostname`
hostname="${hostname%%.*}"
dnsdomainname=`dnsdomainname 2>/dev/null || true`
if [ -n "$dnsdomainname" ]; then
	hostname="$hostname.$dnsdomainname"
fi

ORIG_USER=$USER
USER=
if [ -n "$SUDO_USER" ]; then
	USER="$SUDO_USER"
else
	# try to check tty ownership, in case user su'd to root
	TTY="$(tty 2>/dev/null || true)"
	if [ -n "$TTY" ] && [ -c "$TTY" ]; then
		USER="$(find "$TTY" -printf "%u")"
	fi
fi

if [ "$VCS" = git ] && [ -d .git ]; then
	if [ -n "$USER" ]; then
		# Use user.name and user.email from the gitconfig belonging
		# to the user who became root.
		USER_HOME="$(getent passwd "$USER" | cut -d: -f6)"
		if [ -n "$USER_HOME" ] && [ -e "$USER_HOME/.gitconfig" ]; then
			if [ -z "$GIT_AUTHOR_NAME" ]; then
				GIT_AUTHOR_NAME="$(git config -f "$USER_HOME/.gitconfig" user.name)" || true
				export GIT_AUTHOR_NAME
			fi
			if [ -z "$GIT_AUTHOR_EMAIL" ]; then
				GIT_AUTHOR_EMAIL="$(git config -f "$USER_HOME/.gitconfig" user.email)" || true
				export GIT_AUTHOR_EMAIL
			fi
		fi
		if [ -z "$GIT_AUTHOR_NAME" ] || [ -z "$GIT_AUTHOR_EMAIL" ]; then
			if [ -n "$USER_HOME" ] && [ -e "$USER_HOME/.config/git/config" ]; then
				if [ -z "$GIT_AUTHOR_NAME" ]; then
					GIT_AUTHOR_NAME="$(git config -f "$USER_HOME/.config/git/config" user.name)" || true
					export GIT_AUTHOR_NAME
				fi
				if [ -z "$GIT_AUTHOR_EMAIL" ]; then
					GIT_AUTHOR_EMAIL="$(git config -f "$USER_HOME/.config/git/config" user.email)" || true
					export GIT_AUTHOR_EMAIL
				fi
			fi
		fi

		if [ -z "$GIT_COMMITTER_EMAIL" ]; then
			GIT_COMMITTER_EMAIL="$(git config --global user.email)" || true
			export GIT_COMMITTER_EMAIL
		fi
		if [ -z "$GIT_AUTHOR_NAME" ]; then
			GIT_AUTHOR_NAME="$USER"
			export GIT_AUTHOR_NAME
		fi
		if [ -z "$GIT_AUTHOR_EMAIL" ]; then
			GIT_AUTHOR_EMAIL="$USER@$hostname"
			export GIT_AUTHOR_EMAIL
		fi
		if [ -z "$GIT_COMMITTER_EMAIL" ]; then
			GIT_COMMITTER_EMAIL=`whoami`"@$hostname"
			export GIT_COMMITTER_EMAIL
		fi
	fi
	if [ -n "$logfile" ]; then
		git commit $GIT_COMMIT_OPTIONS -F "$logfile"
	else
		git commit $GIT_COMMIT_OPTIONS
	fi
elif [ "$VCS" = hg ] && [ -d .hg ]; then
	if [ -n "$USER" ]; then
		LOGNAME="$USER"
		export LOGNAME
	fi
	if [ -z "$HGUSER" ]; then
		HGUSER="$USER@$hostname"
		export HGUSER
	fi
	if [ -n "$logfile" ]; then
		hg commit $HG_COMMIT_OPTIONS -l "$logfile"
	else
		hg commit $HG_COMMIT_OPTIONS
	fi
elif [ "$VCS" = bzr ] && [ -d .bzr ]; then
	if [ -z "$EMAIL" ] && [ -n "$USER" ]; then
		EMAIL="$USER <$USER@$hostname>"
		export EMAIL
	else
		bzr whoami >/dev/null 2>&1 || export EMAIL="$ORIG_USER <$ORIG_USER@$hostname>"
	fi
	if [ -n "$logfile" ]; then
		bzr commit $BZR_COMMIT_OPTIONS -F "$logfile"
	else
		bzr commit $BZR_COMMIT_OPTIONS
	fi
elif [ "$VCS" = darcs ] && [ -d _darcs ]; then
	if [ -z "$USER" ]; then
		USER=root
	fi
	if [ -n "$logfile" ]; then
		darcs record --author="$USER" $DARCS_COMMIT_OPTIONS --logfile="$logfile"
	else
		darcs record --author="$USER" $DARCS_COMMIT_OPTIONS
	fi
fi
